### ISSUE TITLE
Linux precompiled library (and additional notes)

### ISSUE THREAD

**Issue by michaliskambi** [Kagamma/cge-effekseer#1]
I'm attaching the Linux (for CPU=x86_64) precompiled shared library of the wrapper. Perhaps you want to include it in your libaries on Google Drive?

[libeffekseer.zip](https://github.com/Kagamma/cge-effekseer/files/7010170/libeffekseer.zip)

Loose notes about my experience on Linux:

1. The library I attach works with `demos/TestEffekseer/` nicely. I copied the `libeffekseer.so` inside the project directory and created a shell script to run `TestEffekseer` with a modified `$LD_LIBRARY_PATH` to include this directory (unlike Windows, on Linux the executable directory is *not* automatically searched for shared libraries).

    ```
    #!/bin/bash
    set -e
    # Include current directory in LD_LIBRARY_PATH, to find effekseer dynamic library
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:./"
    ./TestEffekseer "$@"
    ```

    Now I can run the project by `./run.sh`. Also `castle-engine run` (F9 in CGE editor does it) automatically runs the application using this script, that's a feature I added to [build tool](https://github.com/castle-engine/castle-engine/wiki/Build-Tool#run) when testing [FMOD](https://github.com/castle-engine/castle-engine/wiki/FMOD).

2. I would suggest to place the precompiled wrapper versions in this GitHub repository, not on Google Drive. It would make the libraries versioned along with the rest of integration code (e.g. branches `runtime-1.6` and `runtime-1.61a` would naturally contain the respective library version), and allow to make PRs with new precompiled libraries.

    I know that putting binary auto-generated stuff inside version control is generally discouraged... But when it is the practically easiest way, I feel it is sometimes justified :) The goal is to allow people to run `demos/TestEffekseer` as out-of-the-box as possible. Another idea is to release the precompiled wrapper libraries (maybe also test application) as a GitHub release.

3. I followed your compilations instructions on https://github.com/Kagamma/cge-effekseer . In general it was cool, many thanks for documenting it in details.

     3.1. Inside `wrapper/CMakeLists.txt` I had to change `src` -> `Dev/Cpp` (in 2 include paths and 2 library paths, see https://github.com/castle-engine/Effekseer/commit/4255a3f01b2d44a9157fda148f74e3103603ac19 ). It seems this is the layout of Effekseer repository,  at least now. If yes, maybe you want to make this fix also in `wrapper/CMakeLists.txt` in the https://github.com/Kagamma/cge-effekseer ? 

    3.2. To make the compilation easier, I forked the Effekseer repo, included there your wrapper, and modified the `CMakeLists.txt` as needed. My intention is to have something useful to recompile Effekseer library out-of-the-box as directly as possible. So I will be able to synchronize this easily with both https://github.com/castle-engine/Effekseer/ and https://github.com/Kagamma/cge-effekseer/ and have something where I can always just do `cmake --build .` and get the `libeffekseer.so`. I described this is in https://github.com/castle-engine/Effekseer/blob/master/README_CGE.md  . See my last 3 commits on https://github.com/castle-engine/Effekseer/commits/master .

    In my eyes, maintaining such fork may be good -- hopefully synchronization (with main `effekseer` repo and your `cge-effekseer`) will not be a big issue, and in return others will have easier job getting precompiled library.

    Of course I can give you access to that repo too.

**Comment by Kagamma** [comment]
Thanks for the test. I will include your Linux binary to google drive.

As for AD3, this was due to historic reason. As first I didn't recognize Effekseer's github repository include both the runtime and the editor source code, due to differences in directory structure between it and the official runtime download on the website (you already seen it when you made changes in CMakeList.txt). So I haven't tried github repository yet. I am glad it doesn't need to make many changes to make it to work with the source code on the github repository :)

It would be nice if you give me access to that repository :). I definitely want to apply some patches to make it work with MinGW. I will also update README.md to point users to use that repository instead if they want to build wrapper themselves.

**Comment by michaliskambi** [comment]
> I definitely want to apply some patches to make it work with MinGW. I will also update README.md to point users to use that repository instead if they want to build wrapper themselves.

Excellent, exactly. I invited you to CGE organization on GitHub and you should have access to https://github.com/castle-engine/Effekseer/ (and other CGE repos -- and that's good, I want you to have access there and use it freely; feel free to push things to our repos, we only require using PRs to the main CGE castle-engine/castle-engine repo).
